name: valuebuilder-local

volumes:
  flow_mysql_data:
  flow_redis_data:
  flow_app_node_modules:

  valuebuilder_mysql_data:
  valuebuilder_redis_data:
  valuebuilder_mongodb_data:

  emails_mongo_data:

networks:
  timeline-net:
    driver: bridge
  shared:
    driver: bridge
