server {
    # Docker resolver
    resolver 127.0.0.11 valid=30s;

    client_max_body_size 100M;

    listen 81 default_server;
    listen [::]:81 default_server ipv6only=on;

    server_name  localhost;

    root /var/www/web;
    index api.php;
    # Enable HSTS
    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
         try_files $uri $uri/ /api.php$is_args$args;
    }

    location ~ ^/(api|config|info)\.php(/|$) {
        try_files $uri /api.php =404;
        #fastcgi_pass php-upstream;
        fastcgi_index api.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SYMFONY_ENV 'dev';
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;

        #fastcgi_param DOCUMENT_ROOT $realpath_root;
        #fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_pass php-fpm:9000;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

    # Prevents caching of css/less/js/images, only use this in development
    #location ~* \.(css|less|js|jpg|png|gif|ico)$ {
       # add_header Cache-Control "no-cache, no-store, must-revalidate";
       # add_header Pragma "no-cache";
       # expires 0;
   # }
}
