[PHP]
post_max_size = 200M
upload_max_filesize = 100M
variables_order = EGPCS
pcov.directory = .
max_execution_time=300
max_input_time=300

[opcache]
opcache.enable=0
opcache.enable_cli=0
memory_consumption=1024

[xdebug]
xdebug.mode=debug,develop
xdebug.start_with_request=trigger
xdebug.client_host = host.docker.internal
xdebug.client_port=9003
xdebug.log=/tmp/xdebug.log
xdebug.idekey=VSCODE
