version: "3"
services:
  php:
    container_name: php
    build:
      context: ./php/7.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8000}:8000" #https://localhost:8000/
      # - "${REACT_PORT:-3000}:${REACT_PORT:-3000}"
    environment:
      WWWUSER: "${WWWUSER}"
      XDEBUG_MODE: "debug,develop"  
      XDEBUG_CONFIG: "client_host=host.docker.internal" 
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      DATABASE_URL: "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}?server_version=8.0.32"
      REDIS_HOST: "redis"
      UNIVERSAL_PASSWORD: "${UNIVERSAL_PASSWORD}"
      APP_SECRET: eeb958012d0316021fe1715029b5f326
      SOPHIA_SUPPORT_ADVISOR_ID: "${SOPHIA_SUPPORT_ADVISOR_ID}"
      GOOGLE_RECAPTCHA_SITE_KEY: "${GOOGLE_RECAPTCHA_SITE_KEY}"
      GOOGLE_RECAPTCHA_SECRET: "${GOOGLE_RECAPTCHA_SECRET}"
      GOOGLE_RECAPTCHA_ENABLED: "${GOOGLE_RECAPTCHA_ENABLED}"

    volumes:
      - "../:/var/www/html"
    networks:
      - shared-dev
    depends_on:
      - mysql
      - redis

  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shared-dev
  redis:
    image: redis:6.2
    container_name: redis
    mem_limit: 1G
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - shared-dev

networks:
  shared-dev:
    external: true

volumes:
  db_data:
  redis_data:
